#!/bin/bash

echo "Loading azd .env file from current environment"

# Use the `get-values` azd command to retrieve environment variables from the `.env` file
envValues=$(azd env get-values)

declare -A envDict

# Read the environment variables into an associative array
while IFS= read -r line; do
    if [[ $line =~ ^(.*?)=(.*)$ ]]; then
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]//\"/}" # Remove surrounding quotes
        envDict["$key"]="$value"
    fi
done <<< "$envValues"

ENV_CONTENT="# This file is automatically generated by the setup_local.sh script.
AZURE_OPENAI_ENDPOINT=${envDict['AI_ENDPOINT']}
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${envDict['AZURE_OPENAI_AGENTS_MODEL']}
CONSOLE_LOGGING=False
AZURE_AI_FOUNDRY_CONNECTION_STRING=${envDict['AZURE_AI_FOUNDRY_CONNECTION_STRING']}
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS=true
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS_SENSITIVE=true
APPLICATIONINSIGHTS_CONNECTION_STRING=${envDict['APPLICATIONINSIGHTS_CONNECTION_STRING']}
AZURE_MAPS_CLIENT_ID=${envDict['AZURE_MAPS_CLIENT_ID']}
"

GRADIO_CONTENT=$(cat <<EOF
${ENV_CONTENT}

# Gradio specific settings
SECRET_KEY=$(openssl rand -base64 32)

# Entra ID settings
AAD_CLIENT_ID=${envDict['ENTRA_APP_ID']}
AAD_CLIENT_SECRET=${envDict['ENTRA_APP_SECRET']}
AAD_TENANT_ID=${envDict['AZURE_TENANT_ID']}
AAD_REDIRECT_URI=http://localhost:8001/auth/callback

# StackOverflow settings
STACKOVERFLOW_CLIENT_ID=
STACKOVERFLOW_CLIENT_SECRET=
STACKOVERFLOW_KEY=
STACKOVERFLOW_REDIRECT_URI=http://localhost:8001/auth/stackoverflow/callback
EOF
)

STREAMLIT_CONTENT=$(cat <<EOF
[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "$(openssl rand -base64 32)"

[auth.microsoft]
client_id = "${envDict['ENTRA_APP_ID']}"
authority = "https://login.microsoftonline.com/${envDict['AZURE_TENANT_ID']}"
server_metadata_url = "https://login.microsoftonline.com/${envDict['AZURE_TENANT_ID']}/v2.0/.well-known/openid-configuration"
client_kwargs = { "scope" = "openid profile email" }
EOF
)

mkdir -p ./streamlit_app/.streamlit
printf "%s" "$STREAMLIT_CONTENT" > ./streamlit_app/.streamlit/secrets.toml

printf "%s" "$GRADIO_CONTENT" > ./gradio_app/.env

printf "%s" "$ENV_CONTENT" > ./streamlit_app/.env
printf "%s" "$ENV_CONTENT" > ./agents-workshop/02-single-agent-example/azure-ai-agent/.env
printf "%s" "$ENV_CONTENT" > ./agents-workshop/02-single-agent-example/semantic-kernel-agent/.env
printf "%s" "$ENV_CONTENT" > ./agents-workshop/03-building-custom-tools/03.1.azure-ai-agent-simple-tools/.env
printf "%s" "$ENV_CONTENT" > ./agents-workshop/03-building-custom-tools/03.2.azure-ai-agent-builtin-tools/.env
printf "%s" "$ENV_CONTENT" > ./agents-workshop/03-building-custom-tools/03.3.azure-ai-agent-complex-tools/.env