#!/bin/bash

echo "Loading azd .env file from current environment"

# Use the `get-values` azd command to retrieve environment variables from the `.env` file
envValues=$(azd env get-values)

declare -A envDict

# Read the environment variables into an associative array
while IFS= read -r line; do
    if [[ $line =~ ^(.*?)=(.*)$ ]]; then
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]//\"/}" # Remove surrounding quotes
        envDict["$key"]="$value"
    fi
done <<< "$envValues"

ENV_CONTENT="# This file is automatically generated by the setup_local.sh script.
AZURE_OPENAI_ENDPOINT=${envDict['AI_ENDPOINT']}
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${envDict['AZURE_OPENAI_AGENTS_MODEL']}
CONSOLE_LOGGING=False
AZURE_AI_FOUNDRY_CONNECTION_STRING=${envDict['AZURE_AI_FOUNDRY_CONNECTION_STRING']}
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS=true
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS_SENSITIVE=true
APPLICATIONINSIGHTS_CONNECTION_STRING=${envDict['APPLICATIONINSIGHTS_CONNECTION_STRING']}
AZURE_MAPS_CLIENT_ID=${envDict['AZURE_MAPS_CLIENT_ID']}
"

printf "%s" "$ENV_CONTENT" > ./demo_app/.env
printf "%s" "$ENV_CONTENT" > ./agents-workshop/02-single-agent-example/azure-ai-agent/.env
printf "%s" "$ENV_CONTENT" > ./agents-workshop/02-single-agent-example/semantic-kernel-agent/.env