Write-Host "Loading azd .env file from current environment"

# Use the `get-values` azd command to retrieve environment variables from the `.env` file
$envValues = azd env get-values

$envDict = @{}

foreach ($line in $envValues -split "`n") {
    if ($line -match '^(.*?)=(.*)$') {
        $key = $Matches[1]
        $value = $Matches[2].Trim('"') # Remove surrounding quotes
        $envDict[$key] = $value
    }
}

$cookie_secret = [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 }) -as [byte[]])

# Build the .env content using keys from envDict
$envContent = @"
# This file is automatically generated by the setup_local.ps1 script.
AZURE_OPENAI_ENDPOINT=$($envDict['AI_ENDPOINT'])
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=$($envDict['AZURE_OPENAI_AGENTS_MODEL'])
CONSOLE_LOGGING=False
AZURE_AI_FOUNDRY_CONNECTION_STRING=$($envDict['AZURE_AI_FOUNDRY_CONNECTION_STRING'])
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS=true
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS_SENSITIVE=true
APPLICATIONINSIGHTS_CONNECTION_STRING=$($envDict['APPLICATIONINSIGHTS_CONNECTION_STRING'])
AZURE_MAPS_CLIENT_ID=$($envDict['AZURE_MAPS_CLIENT_ID'])
"@

$STREAMLIT_CONTENT=@"
[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "$cookie_secret"

[auth.microsoft]
client_id = "$($envDict['ENTRA_APP_ID'])"
client_secret = "$($envDict['ENTRA_APP_SECRET'])"
server_metadata_url = "https://login.microsoftonline.com/$($envDict['AZURE_TENANT_ID'])/v2.0/.well-known/openid-configuration"
client_kwargs = { "scope" = "openid profile email" }
"@

# Write to .env files
$envContent | Set-Content ./demo_app/.env
$envContent | Set-Content ./agents-workshop/02-single-agent-example/azure-ai-agent/.env
$envContent | Set-Content ./agents-workshop/02-single-agent-example/semantic-kernel-agent/.env
$envContent | Set-Content ./agents-workshop/03-building-custom-tools/03.1.azure-ai-agent-simple-tools/.env
$envContent | Set-Content ./agents-workshop/03-building-custom-tools/03.2.azure-ai-agent-builtin-tools/.env